//! Per-variant error breakdowns generated by `#[metered::error_count]`.
//!
//! An error-count enum generates a struct of per-variant counters that
//! implements [`ErrorBreakdownIncr`]. When measured, the breakdown classifies a
//! result's error via [`ClassifyError`] (which supports wrapped error types)
//! and increments the matching variant through an [`ErrorBreakdownRecorder`].

use crate::metric::Recorder;

/// Trait applied to error enums by `#[error_count]` to identify their generated
/// error-count struct.
pub trait ErrorBreakdown {
    /// The generated error count struct.
    type ErrorCount;
}

/// Implemented by a generated breakdown struct to increment the counter for a
/// specific error variant.
///
/// The associated [`ErrorBreakdownIncr::Error`] type is the error enum the
/// breakdown was generated for; it is what lets a breakdown be used with wrapped
/// error types via [`ClassifyError`].
pub trait ErrorBreakdownIncr {
    /// The error enum this breakdown counts.
    type Error;

    /// Increase the count for the given variant by 1.
    fn incr(&self, e: &Self::Error);
}

/// Classifies a measured result into the error variant an
/// [`ErrorBreakdownIncr`] should count.
///
/// It is blanket-implemented for `Result<T, E>` (returning the `Err` value), so
/// breakdowns work out of the box on plain results. To use a breakdown with a
/// **wrapped** error -- e.g. a method returning `Result<T, Wrapper<MyError>>`
/// where `#[error_count]` was applied to `MyError` -- implement this trait for
/// the wrapper result, projecting to the inner enum:
///
/// ```ignore
/// impl<T> ClassifyError<MyError> for Result<T, Wrapper<MyError>> {
///     fn error_variant(&self) -> Option<&MyError> {
///         self.as_ref().err().map(|w| &w.inner)
///     }
/// }
/// ```
pub trait ClassifyError<E> {
    /// The error variant to count, if the outcome was an error.
    fn error_variant(&self) -> Option<&E>;
}

impl<T, E> ClassifyError<E> for Result<T, E> {
    fn error_variant(&self) -> Option<&E> {
        self.as_ref().err()
    }
}

/// Recorder used by `#[error_count]`-generated breakdown metrics.
///
/// It owns a (cheaply-shared) handle to the breakdown's counters, so it does not
/// borrow the metric across the measured expression. On normal completion it
/// increments the counter for the returned error variant (via [`ClassifyError`],
/// which also supports wrapped error types); a panic / cancellation has no
/// variant and so is not attributed here (the aggregate
/// [`ErrorCount`](crate::ErrorCount) still records it).
pub struct ErrorBreakdownRecorder<M> {
    metrics: M,
}

impl<M> ErrorBreakdownRecorder<M> {
    /// Builds a recorder over an owned (shared) handle to the breakdown metrics.
    pub fn new(metrics: M) -> Self {
        ErrorBreakdownRecorder { metrics }
    }
}

impl<M, R> Recorder<R> for ErrorBreakdownRecorder<M>
where
    M: ErrorBreakdownIncr,
    R: ClassifyError<M::Error>,
{
    fn complete(&mut self, result: &R) {
        if let Some(e) = result.error_variant() {
            self.metrics.incr(e);
        }
    }
}
